version: "3.9"

services:
  app:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - .:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - SQLITE_PATH=/app/data/local.db

  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017" 
    volumes:
      - ./mongo_data:/data/db
